# Generated by Django 4.2.3 on 2023-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_fl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=150, verbose_name='Slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('Imag', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Превью')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('number_of_views', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'Блоги',
                'db_table': 'blog',
                'db_table_comment': 'Блог и комментарии',
                'ordering': ['number_of_views'],
            },
        ),
    ]
