# Generated by Django 4.2.3 on 2023-07-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_blog_fl_number_of_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_fl',
            name='number_of_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
